config/routes.rb
Rails.application.routes.draw do

  devise_for :teachers, controllers: { sessions: "sessions" }

  resources :schedules, only: :index do
    get :calendar, on: :collection
    post :assign, on: :collection
    post :pick_courses, on: :collection
    post :set_courses, on: :member
    get :view, on: :collection
  end

  root 'routes#root'

end

app/models/availability.rb
class Availability < ActiveRecord::Base
	belongs_to :user
  validates_presence_of :start_time, :end_time

	enum day: [:Dom, :Lun, :Mar, :Mie, :Jue, :Vie, :Sab]

end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :faculty
  has_many :course_teachers, dependent: :destroy
end

app/models/course_teacher.rb
class CourseTeacher < ActiveRecord::Base
	belongs_to :teacher
  belongs_to :course
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_many :courses, dependent: :destroy
  has_many :faculty_teachers, dependent: :destroy
end

app/models/faculty_teacher.rb
class FacultyTeacher < ActiveRecord::Base
	belongs_to :teacher
	belongs_to :faculty
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :availabilities, dependent: :destroy
  has_many :faculty_teachers, dependent: :destroy
  has_many :faculties, through: :faculty_teachers
  has_many :course_teachers, dependent: :destroy
  has_many :courses, through: :course_teachers

  after_create :update_properties

  enum category: [:principal, :associated, :exclusive_dedication, :auxiliary]
  enum class_hours: {eight: 8, twenty: 20, fourty: 40}

  validate :validate_username
  validates :username, presence: true
  
  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
  	# Agregar OR lower(email) = :value en el caso de que el login sea tanto con username como con email (por si las pepes)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end


	def validate_username
	  if Teacher.where(email: username).exists?
	    errors.add(:username, :invalid)
	  end
	end

  def name
  	"#{first_name} #{last_name}"
  end

  def update_properties
    self.update(class_hours: Teacher.class_hours.keys.sample)
    case Teacher.class_hours[self.class_hours]
    when 8
      self.update(past_hours: 8)
    when 20
      self.update(past_hours: rand(14..20))
    when 40 
      self.update(past_hours: rand(14..20))
    end
    self.update(category: rand(0..3))
    FacultyTeacher.create(faculty_id: 1, teacher_id: self.id)
  end

  def hour_selected? col, row
    av = self.availabilities.find_by(day: col.to_i, start_time: (row.to_i + 8), end_time:(row.to_i + 9))
    av.blank? ? false : true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_teacher!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_teacher_session_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :current_password, :phone) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :first_name, :last_name, :email, :password, :current_password, :phone) }
    end
end

app/controllers/routes_controller.rb
class RoutesController < ActionController::Base
  before_filter :authenticate_teacher!

  def root
    if current_teacher.can_edit?
      root_p = schedules_path
    else
      root_p = view_schedules_path
    end
    redirect_to root_p
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	def index
		@eap = Faculty.where(parent_id: 1)
	end

	def calendar
	end

	def assign
		if current_teacher.can_register?
	  	@status = "Antes tiene que registrar sus cursos."
		else
			if current_teacher.can_edit?
		    unless (params[:days_ids].blank? and params[:hours_ids].blank?)
					size = params[:hours_ids].size
					if size > (current_teacher.past_hours.to_i - 1) and size <= Teacher.class_hours[current_teacher.class_hours]
						current_teacher.update(current_hours: size)
						size.times do |i|
							if current_teacher.can_edit?
								new_availability = current_teacher.availabilities.create(day: params[:days_ids][i].to_i, start_time: (params[:hours_ids][i].to_i + 8), end_time:(params[:hours_ids][i].to_i + 9))
				      end
				    end
					else
						if Teacher.class_hours[current_teacher.class_hours] == 8
			  			@status = "Debe escojer una cantidad de horas igual a 8."
						else
			  			@status = "Debe escojer una cantidad de horas mayor a " + current_teacher.past_hours + " y menor o igual a " + Teacher.class_hours[current_teacher.class_hours].to_s + "."
						end
					end
			  else
			  	@status = "Debe registrar un horario para continuar."
		    end
		    current_teacher.update(can_edit: false) if @status.blank?
			else
		  	@status = "No tiene permisos para editar el horario, ya fue registrado anteriormente con éxito."
			end
		end
	end

	def pick_courses
		@can_edit = current_teacher.can_edit
		if current_teacher.can_register?
			if params["Select EAP"].blank?
				@status = "Debe seleccionar una escuela académico profesional."
			else
				if params[:courses].blank?
					@status = "Debe elegir al menos un curso."
				else
					current_teacher.courses = Course.where(id: params[:courses])
	    		current_teacher.update(can_register: false)
				end
			end
		else
			@status = "Ya no tiene permisos para editar, los cursos ya fueron registrados con éxito."
		end
	end

	def set_courses
		@courses = Course.where(faculty_id: params[:id])
	end

	def view
	end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def destroy
  	if current_teacher.can_register? or current_teacher.can_edit?
  		current_teacher.courses = []
  		current_teacher.availabilities = []
  		current_teacher.save
  		current_teacher.update(can_register: true)
  		current_teacher.update(can_edit: true)
  	end
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    yield if block_given?
    respond_to_on_destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_enum_for_select class_name, enum_name
    class_name.constantize.send(enum_name.pluralize).keys.map {|k| [k.humanize, k]}
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>SDD</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>.:: SDD ::.</title>
	  <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'devise', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body class="back-color">
		<div class="container">
			<div id="errors-login" class="col-md-12">
				<%= render 'layouts/messages' %>
			</div>
			<%= yield %>
		</div>
	</body>
</html>

app/views/schedules/_listing_courses.html.erb
<% if courses.blank? %>
  Ningún curso se ha seleccionado
<% else %>
	<table>
		<thead></thead>
		<tbody>
		  <% courses.each do |c| %>
			  	<tr>
			  		<td>
		      		<%= check_box_tag 'courses[]', c.id, false, id:"course_#{c.id}", disabled: !current_teacher.can_register? %>
			  		</td>
			  		<td class="padding-td">
		    			<label for="course_<%= c.id %>">
			      		<%= c.name %>
		    			</label>
			  		</td>
			  	</tr>
		  <% end %>
		</tbody>
	</table>
<% end %>

app/views/schedules/calendar.html.erb
<div>
	<h2>Registrando mi horario semanal</h2>
</div>
<div class="col-md-12">
	<div>
		<% if teacher_signed_in? %>
		  <%= link_to 'Cerrar sesión', destroy_teacher_session_path, method: :delete, class:"btn btn-danger pull-right
		  " %>
		<% end %>
	</div>
	<div class="col-md-2"></div>
	<div class="col-md-8">
	  <%= form_tag assign_schedules_path, remote: true do %>
			<%= submit_tag 'Guardar', id:"button-save-calendar", class:"btn btn-primary pull-right", data: { confirm: "El horario registrado no podrá ser modificado en el futuro. ¿Desea continuar?", disable_with: "Guardando ..." } %>
			<% if Teacher.class_hours[current_teacher.class_hours] == 8 %>
				<b>Cantidad de horas a registrar: <%= current_teacher.past_hours %></b>
			<% else %>
				<span>Cantidad de horas a superar: <b><%= current_teacher.past_hours %></b></span><br>
				<span>Cantidad de horas máximas a registrar: <b><%= Teacher.class_hours[current_teacher.class_hours] %></b></span>
			<% end %>
			<table class="table table-bordered">
				<thead></thead>
			  	<tr>
			  		<th class="centered">HORAS</th>
			      <% Availability.days.each_with_index do |(key, value), index| %>
			    		<th class="centered"><%= key %></th>
						<% end %>
			  	</tr>
				<tbody>
					<% 14.times do |i| %>
						<tr>
							<td class="centered"><%= "#{i + 8}:00 - #{i + 9}:00" %></td>
							<% 7.times do |j| %>
								<td onclick="<%= "javascript:select_time(this, #{i}, #{j})" if current_teacher.can_edit %>" class="<%= 'green' if current_teacher.hour_selected?(j, i) %>">
		              <%= check_box_tag "hours_ids[]", "#{i}", nil, id:"dayc-#{i}-r-#{j}", class:"hide" %>
		              <%= check_box_tag "days_ids[]", "#{j}", nil, id:"hourc-#{i}-r-#{j}", class:"hide" %>
								</td>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% end %>
	</div>
	<div class="col-md-2"></div>
</div>

app/views/schedules/index.html.erb
<div>
	<h1>Registro de Datos</h1>
	<div>
		<% if teacher_signed_in? %>
		  <%= link_to 'Cerrar sesión', destroy_teacher_session_path, method: :delete, class:"btn btn-danger pull-right
		  " %>
		<% end %>
	</div>
	<h3>Bienvenido(a): <%= current_teacher.name %></h3>
</div>
<div class="col-md-12">
	<div class="col-md-7">
		<div class="panel panel-success">
			<div class="panel-heading">
				<b>Datos Básicos</b>
			</div>
			<div class="panel-body">
				<table>
					<thead></thead>
					<tbody>
						<tr>
							<td><b>NOMBRES:</b></td>
							<td class="basic-left-margin"><%= current_teacher.first_name %></td>
						</tr>
						<tr>
							<td><b>APELLIDOS:</b></td>
							<td class="basic-left-margin"><%= current_teacher.last_name %></td>
						</tr>
						<tr>
							<td><b>CÓDIGO:</b></td>
							<td class="basic-left-margin"><%= current_teacher.username %></td>
						</tr>
						<tr>
							<td><b>TELÉFONO:</b></td>
							<td class="basic-left-margin"><%= current_teacher.phone %></td>
						</tr>
						<tr>
							<td><b># HRS PASADAS:</b></td>
							<td class="basic-left-margin past-hours"><b><%= current_teacher.past_hours %></b></td>
						</tr>
						<tr>
							<td><b>CATEGORÍA:</b></td>
							<td class="basic-left-margin"><%= t (current_teacher.category) %></td>
						</tr>
						<tr>
							<td><b>CLASE:</b></td>
							<td class="basic-left-margin"><b><%= Teacher.class_hours[current_teacher.class_hours] %> horas</b></td>
						</tr>
						<tr>
							<td><b>FACULTAD:</b></td>
							<td class="basic-left-margin"><%= current_teacher.faculties.first.name %></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-5"></div>
</div>
<div class="col-md-12">
	<div class="col-md-7">
		<div class="panel panel-info">
			<div class="panel-heading">
				<b> Registro de Cursos </b>
			</div>
			<div class="panel-body">
  			<%= form_tag pick_courses_schedules_path, remote: true do %>
					<div class="col-md-12">
						<div class="col-md-6">
							<%= select_tag 'Select EAP', options_from_collection_for_select(@eap, "id", "name", selected: ''), include_blank: '- Selección de EAP -', disabled: !current_teacher.can_register?, id:'faculty-type-select', class:"form-control", onchange:"javascript:set_courses()" %>
						</div>
						<div id="list-courses" class="col-md-6">
							<%= render 'listing_courses', courses: @courses %>
						</div>
					</div>
					<div class="col-md-12 info-margin">
  					<%= submit_tag 'Guardar', class:"btn btn-primary pull-right", data: { confirm: "Los datos registrados no podrán ser modificados en el futuro. ¿Desea continuar?", disable_with: "Guardando ..." } %>
					</div>
  			<% end %>
			</div>
		</div>
	</div>
	<div class="col-md-5"></div>
</div>

app/views/schedules/view.html.erb
<h1><%= current_teacher.name %> <small>- Datos Generales</small></h1>
<div>
	<% if teacher_signed_in? %>
	  <%= link_to 'Cerrar sesión', destroy_teacher_session_path, method: :delete, class:"btn btn-danger pull-right
	  " %>
	<% end %>
</div>
<div class="col-md-7">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<b>Datos Básicos</b>
		</div>
		<div class="panel-body">
			<table class="table details" width="100%">
				<thead></thead>
				<tbody>
					<tr>
						<td><b>NOMBRES:</b></td>
						<td><%= current_teacher.first_name %></td>
					</tr>
					<tr>
						<td><b>APELLIDOS:</b></td>
						<td><%= current_teacher.last_name %></td>
					</tr>
					<tr>
						<td><b>CÓDIGO:</b></td>
						<td><%= current_teacher.username %></td>
					</tr>
					<tr>
						<td><b>TELÉFONO:</b></td>
						<td><%= current_teacher.phone %></td>
					</tr>
					<tr>
						<td><b># HRS PASADAS:</b></td>
						<td class="basic-left-margin past-hours"><b><%= current_teacher.past_hours %></b></td>
					</tr>
					<tr>
						<td><b># HRS ACTUALES:</b></td>
						<td class="basic-left-margin current-hours"><b><%= current_teacher.current_hours %></b></td>
					</tr>
					<tr>
						<td><b>CATEGORÍA:</b></td>
						<td><%= t (current_teacher.category) %></td>
					</tr>
					<tr>
						<td><b>CLASE:</b></td>
						<td><b><%= Teacher.class_hours[current_teacher.class_hours] %> horas</b></td>
					</tr>
					<tr>
						<td><b>FACULTAD:</b></td>
						<td><%= current_teacher.faculties.first.name %></td>
					</tr>
					<tr>
						<td><b>CURSOS REGISTRADOS:</b></td>
						<td>
							<% current_teacher.courses.each do |course| %>
								<%= course.name %><br>
							<% end %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="col-md-5"></div>
<div class="col-md-12">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<b>Horario Registrado</b>
		</div>
	  <div class="panel-body">
			<table class="table table-bordered">
				<thead></thead>
			  	<tr>
			  		<th class="centered">HOURS</th>
			      <% Availability.days.each_with_index do |(key, value), index| %>
			    		<th class="centered"><%= key %></th>
						<% end %>
			  	</tr>
				<tbody>
					<% 14.times do |i| %>
						<tr>
							<td class="centered"><%= "#{i + 8}:00 - #{i + 9}:00" %></td>
							<% 7.times do |j| %>
								<td class="<%= 'green' if current_teacher.hour_selected?(j, i) %>">
								</td>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
	  </div>
	</div>
</div>